[package]
name = "cypress"
version = "0.1.1"
edition = "2024"
description = "Build simple yet expressive parsers"
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/noahcape/cypress" 
keywords = ["parser", "combinator"]
categories = ["parsing"]